apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: apim-tryitnow-slc
spec:
  values:
    global:
      enableKeyVaults: true
    java:
      ingressHost: apim-tryitnow-slc.sandbox.platform.hmcts.net
      workloadClientID: "775648eb-07db-4354-90f6-f0bca549341b"
      environment:
        APPLICATIONINSIGHTS_ENABLED: "false"
        APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=00000000-0000-0000-0000-000000000000"
      keyVaults:
        apim-sbox:
          excludeEnvironmentSuffix: true
          secrets:
            - name: tryitnow-slc-DEMO-SIGNING-KEY-JWK
              alias: DEMO_SIGNING_KEY_JWK
            - name: tryitnow-slc-POSTGRES-USER
              alias: POSTGRES_USER
            - name: tryitnow-slc-POSTGRES-PASS
              alias: POSTGRES_PASS
            - name: tryitnow-slc-POSTGRES-HOST
              alias: POSTGRES_HOST
            - name: tryitnow-slc-POSTGRES-PORT
              alias: POSTGRES_PORT
            - name: tryitnow-slc-POSTGRES-DATABASE
              alias: POSTGRES_DATABASE
